App\Entity\Calls:
    type: entity
    table: closeio_call
    repositoryClass: App\Repository\CallsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        voicemailUrl:
            type: text
            nullable: true
            column: voicemail_url
        dateUpdated:
            type: datetime
            nullable: true
            column: date_updated
        createdByName:
            type: string
            length: 255
            nullable: true
            column: created_by_name
        type:
            type: string
            length: 255
            nullable: true
            column: _type
        contactId:
            type: string
            length: 255
            nullable: true
            column: contact_id
        duration:
            type: integer
            nullable: true
        closeId:
            type: string
            length: 255
            unique: true
            column: close_id
        updatedByName:
            type: string
            length: 255
            nullable: true
            column: updated_by_name
        users:
            type: array
            nullable: true
        userId:
            type: string
            length: 255
            nullable: true
            column: user_id
        voicemailDuration:
            type: integer
            nullable: true
            column: voicemail_duration
        transferredFrom:
            type: string
            length: 255
            nullable: true
            column: transferred_from
        createdBy:
            type: string
            length: 255
            nullable: true
            column: created_by
        note:
            type: text
            nullable: true
        source:
            type: string
            nullable: true
            length: 255
        hasRecording:
            type: boolean
            nullable: true
            column: has_recording
        dialerId:
            type: string
            length: 255
            nullable: true
            column: dialer_id
        userName:
            type: string
            length: 255
            nullable: true
            column: user_name
        status:
            type: string
            length: 255
            nullable: true
        direction:
            type: string
            length: 255
            nullable: true
        localPhoneFormatted:
            type: string
            length: 255
            nullable: true
            column: local_phone_formatted
        updatedBy:
            type: string
            length: 255
            nullable: true
            column: updated_by
        organizationId:
            type: string
            length: 255
            column: organization_id
            nullable: true
        localPhone:
            type: string
            length: 255
            nullable: true
            column: local_phone
        leadId:
            type: string
            length: 255
            nullable: true
            column: lead_id
        transferredTo:
            type: string
            length: 255
            nullable: true
            column: transferred_to
        dateCreated:
            type: datetime
            column: date_created
        recordingUrl:
            type: text
            nullable: true
            column: recording_url
    lifecycleCallbacks: {  }
