eight_points_guzzle:
    clients:
        close:
            base_url: '%close_io_base_url%'

            options:
                timeout: 100

                headers:
                    Authorization: "%close_io_auth_basic%"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~

services:
    GuzzleHttp\Client: '@eight_points_guzzle.client.close'
